# Generated by Django 5.2 on 2025-04-04 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата проведения')),
                ('notification', models.FileField(upload_to='notifications/', verbose_name='Уведомление (подписано ЭП)')),
                ('meeting_type', models.CharField(choices=[('vote', 'Заочное голосование'), ('online', 'Дистанционное участие')], max_length=50, verbose_name='Форма проведения')),
                ('voting_start_time', models.DateTimeField(verbose_name='Время начала голосования')),
                ('voting_end_time', models.DateTimeField(verbose_name='Время окончания голосования')),
            ],
        ),
        migrations.CreateModel(
            name='AgendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название вопроса')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
                ('materials', models.FileField(upload_to='materials/', verbose_name='Материалы (подписаны ЭП)')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_items', to='main.meeting')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('yes', 'За'), ('no', 'Против'), ('abstain', 'Воздержался')], max_length=10, verbose_name='Голос')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время голоса')),
                ('signed_vote', models.FileField(upload_to='signed_votes/', verbose_name='Подписанный опросный лист (ЭП)')),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='main.agendaitem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
