# Generated by Django 5.2 on 2025-04-05 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='meeting_type',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='notification',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='voting_end_time',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='voting_start_time',
        ),
        migrations.AddField(
            model_name='agendaitem',
            name='meeting_type',
            field=models.CharField(choices=[('vote', 'Заочное голосование'), ('online', 'Дистанционное участие')], default=1, max_length=50, verbose_name='Форма проведения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель конференции'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='link',
            field=models.CharField(default='link', verbose_name='Сссылка на коференцию'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='user_photos/', verbose_name='Фото')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
