# Generated by Django 5.2 on 2025-04-05 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_meeting_link_meeting_registration_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaitem',
            name='summary_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата и время подведения итогов'),
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='materials',
            field=models.FileField(blank=True, null=True, upload_to='materials/', verbose_name='Материалы (подписаны ЭП)'),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='registration_link',
            field=models.CharField(max_length=255, verbose_name='Ссылка на регистрацию на конференцию'),
        ),
    ]
