# Generated by Django 5.2 on 2025-04-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_agendaitem_summary_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='name_room',
            field=models.CharField(default='first room', max_length=255, verbose_name='Название комнаты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendaitem',
            name='summary_datetime',
            field=models.DateTimeField(default='2025-04-10', verbose_name='Дата и время подведения итогов'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='signed_vote',
            field=models.FileField(blank=True, null=True, upload_to='signed_votes/', verbose_name='Подписанный опросный лист (ЭП)'),
        ),
    ]
